In [4]:
!pip install pandas numpy matplotlib scikit-learn seaborn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\magal\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (2.0.3)
Requirement already satisfied: numpy in c:\users\magal\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (1.26.3)
Requirement already satisfied: matplotlib in c:\users\magal\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (3.8.4)
Requirement already satisfied: scikit-learn in c:\users\magal\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (1.7.2)
Requirement already satisfied: seaborn in c:\users\magal\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\magal\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\magal\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\magal\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas) (2023.4)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\magal\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib) (1.2.1)
Requirement already satisfied: cycler>=0.10 in c:\users\magal\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\magal\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\magal\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib) (1.4.5)
Requirement already satisfied: packaging>=20.0 in c:\users\magal\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib) (24.0)
Requirement already satisfied: pillow>=8 in c:\users\magal\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib) (10.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\magal\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from matplotlib) (3.1.2)
Requirement already satisfied: scipy>=1.8.0 in c:\users\magal\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\magal\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\magal\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in c:\users\magal\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip is available: 25.0.1 -> 25.2
[notice] To update, run: C:\Users\magal\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [5]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import random
from sklearn.model_selection import train_test_split

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/aprendizaje-automatico-dc-uba-ar/material/blob/main/tp/01_aprendizaje_supervisado/tp01-enunciado.ipynb)

# Trabajo Práctico -  Aprendizaje supervisado
### Clasificación de expresiones genómicas

<span style="color: red;">**Fecha de entrega: 02 de Octubre del 2025 - hasta las 9:00hs.**
 
<span style="color: red;">**Fecha de entrega intermedia: 23 de Septiembre del 2025 - hasta las 9:00hs.**
</span>

## Introducción

En el mundo actual, distintas disciplinas científicas empiezan, cada vez más, a interactuar con el fin de potenciar sus descubrimientos. En este caso dos grupos de investigación de [CONICET](https://www.conicet.gov.ar/) se embarcan en la combinación entre biología y informática para abordar la detección temprana y el pronóstico preciso de enfermedades como el cáncer. Este proyecto combina las tecnologías de secuenciación de nueva generación ([_NGS_](https://es.wikipedia.org/wiki/Secuenciaci%C3%B3n_paralela_masiva), por sus siglas en inglés) con la potencia de la inteligencia artificial. El enfoque se centra en un dataset único que abarca mediciones de [_ARN_](https://es.wikipedia.org/wiki/ARN_mensajero) de 200 [_genes_](https://es.wikipedia.org/wiki/Gen), recopiladas de pacientes con lesiones [_pre-tumorales_](https://en.wikipedia.org/wiki/Hyperplasia). Este conjunto de datos se convierte en una valiosa fuente de información para entender cómo las células en estado de hiperplasia pueden evolucionar hacia [_tumores malignos_](https://en.wikipedia.org/wiki/Neoplasm), una transformación que ha desconcertado a la ciencia durante décadas.

La hiperplasia, es un fenómeno en el que las células experimentan un crecimiento anormal y descontrolado, es un punto de partida crucial en nuestro análisis. ¿Cómo y por qué algunas células que experimentan hiperplasia se convierten en células cancerosas, mientras que otras no? Esta pregunta es el corazón de nuestra investigación. Para responderla se realizo un estudio donde se obtuvieron muestras de distintos tipos de hiperplasias de pacientes con antecedentes familiares y lesiones pre tumorales. Este grupo de pacientes, o cohorte, fue monitoreado periodicamente durante los siguientes 5 años buscando indicios de neoplasias o nuevas hiperplasias más agresivas. Con las muestras obtenidas en este estudio se realizo un [_biobanco_](https://en.wikipedia.org/wiki/Biobank) con las mediciones que habitualmente se hacen en la construccion de este tipo de [_plataformas_](https://xena.ucsc.edu/). Cada muestra fue etiquetada como **_buen pronostico_**, si no hubo indicios de nuevas hiperplasias o similares; contrariamente se etiquetaron como de **_mal pronostico_** si hubo una recaida.

Este trabajo se concentra en un panel de genes, especificamente en la expresion de 200 genes que se creen tienen un papel crucial en la transformacion tumoral y su etiqueta correspondiente.

En concreto:

Tendrán un archivo `.csv` en donde se almacenan:
  - una matriz de datos `X` de $500$ filas en donde cada fila $x^{(i)}$ representa un vector de $200$ características de cada instancia. Es decir, $\textbf{x}^{(i)} = x_1^{(i)}, \dots, x_{200}^{(i)}$ con $i$ entre $1$ y $500$.
  - una columna llamada `target` que representa un vector de $500$ posiciones con dos posibles valores: `True` (ó 1, es decir, tiene buen pronostico) y `False` (ó 0, tiene mal pronostico).

Los datos están en esta [carpeta](https://github.com/aprendizaje-automatico-dc-uba-ar/material/tree/main/tp/01_aprendizaje_supervisado/datos).

Por otra parte, tendrán disponibles un conjunto de instancias sin etiquetas, que utilizaremos para comprobar la calidad de sus resultados (ver Ejercicio 4). 

**Recomendamos fuertemente leer primero todo el enunciado del trabajo antes de empezar a trabajar sobre el problema propuesto.**

---

### Sobre el informe

Para este trabajo deberán entregar, además del código de las pruebas y experimentos que realicen, un informe en el que deberan seleccionar, para cada apartado, sus resultados acompañado de un texto que explique, reflexione, justifique y conluya dicho contenido. 

Cada ejercicio indica el largo máximo del texto que se puede incluir. Los gráficos no están contados en dicho espacio. 
Cada gráfico incluido debe contar con:
  
  - nombres de los ejes,
  - título,
  - leyenda autocontenida,
  - debe ser referenciado desde el texto, ya que su inclusión se da porque aporta a la discusión del trabajo.

**El informe no puede superar un máximo de 8 carillas (contando gráficos) o 4 hojas más carátula.** No se corregirán trabajos que no cumplan con esta consigna.

---

## Ejercicio 1 

### Separación de datos

Contarán con una cantidad limitada de datos, por lo cual es importante tomar una buena decisión en el momento de empezar a utilizarlos. 

Evaluar y justificar cómo separarán sus datos para desarrollo y para evaluación. ¿Qué consideraciones tuvieron en cuenta para realizar esta división?

**Importante**: en este punto no está permitido dividir la base de datos utilizando la función `train_test_split` de sklearn. Deben decidir e implementar la separación.

In [6]:
df = pd.read_csv("datos/data.csv")
class_mask_0 = df["target"]==0
class_mask_1 = df["target"]==1
df[class_mask_0]

,uAro,vIlg,VtZP,qTUs,bgVs,PdRG,CqGH,bfBD,ZtLG,SNCN,...,hnYp,cWwQ,GkqC,VHPu,KKxk,TNkz,GkcC,KSYM,YpTu,target
2,-0.160656,-1.011420,-0.216399,0.797341,5.672563,7.822798,0.806452,0.386419,-0.854304,0.003736,...,1.411142,2.481312,0.492739,-3.132938,-22.681919,-1.066736,-0.041351,-0.311166,-1.299748,0
3,1.128357,0.341273,-1.669474,0.767591,-4.610520,-8.788584,2.272761,-0.762237,-0.245964,-0.101648,...,1.418474,-0.555290,-0.400534,0.149306,-8.262423,-4.142330,1.256389,-1.252168,-1.597531,0
4,0.573025,1.278193,0.112418,-1.431578,0.589556,1.913852,0.021793,0.533563,0.321761,-0.108064,...,-0.487612,-0.818391,-0.158147,-4.996113,-18.901603,-1.276128,0.318565,-0.592519,1.788781,0
5,0.069392,0.366431,0.245100,0.438993,4.869485,5.005705,-1.923768,0.363241,0.244752,-1.996205,...,-0.755775,-0.747498,0.264077,-2.931813,15.057839,0.525650,-1.118179,0.733938,0.335569,0
6,-0.557834,-0.937319,-0.648424,-0.331217,-3.087285,-2.405165,-0.729081,0.569683,1.512115,-0.017688,...,0.595378,-0.932116,-0.723574,-1.136253,-8.650371,0.178844,0.107175,-1.074904,0.918250,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
493,-1.612282,-0.716976,-0.601632,-2.990996,-1.388879,-1.057568,-0.786217,0.282585,-0.427418,1.579539,...,-0.432287,0.234861,-0.169649,-3.014244,-19.638231,-4.627144,-0.077422,-0.042252,-0.240697,0
494,-0.086170,-0.162519,1.374055,2.459149,6.061579,-4.011132,-0.819642,0.327791,-0.283817,0.169519,...,1.050754,-0.675227,-0.570243,-1.527910,-23.397243,0.966145,0.394092,0.482706,0.882700,0
495,-0.203604,1.812541,0.059184,1.398556,-0.485951,-7.884101,0.356899,1.329484,-2.224481,0.572397,...,-0.820242,1.293028,1.233058,-4.127304,-6.917224,4.888046,1.080738,0.686450,-0.630525,0
496,0.965828,-0.740102,-1.681491,1.122918,-6.679373,-5.881964,0.769760,-1.114970,1.264902,0.016951,...,0.412721,1.439696,1.565305,1.908075,2.251640,3.026561,1.675971,-0.966997,-0.607276,0
498,0.426267,0.353397,-1.217289,-0.567143,-1.005736,5.650036,-0.538329,-0.416654,0.793218,0.187432,...,0.356672,0.966733,-1.228976,-3.020635,10.170147,-3.359936,-0.389039,-0.536885,-0.620916,0

In [7]:
sets = train_test_split(df)
sets[0]

,uAro,vIlg,VtZP,qTUs,bgVs,PdRG,CqGH,bfBD,ZtLG,SNCN,...,hnYp,cWwQ,GkqC,VHPu,KKxk,TNkz,GkcC,KSYM,YpTu,target
491,-1.144066,-0.665135,1.745811,0.669009,0.907020,-3.975619,0.925547,-1.100691,0.605987,-0.469792,...,1.393127,0.867799,1.113843,-0.375458,3.148844,-2.757318,-1.609742,0.726112,-0.833219,0
419,0.339888,-0.293637,0.938846,0.477098,1.426631,0.361727,2.354470,0.092892,-0.046774,0.067412,...,-0.190228,-0.820570,1.393894,-5.021323,-16.874744,-5.155108,0.583573,0.755124,-0.178322,0
189,-0.248982,-0.545399,1.500985,-0.008499,3.355836,4.935880,-0.676613,0.368752,-0.387410,-0.556824,...,-0.284250,-0.655391,-0.367834,0.898111,10.521285,6.055075,-0.345810,-0.328196,1.209891,0
385,-1.050136,-1.218810,-0.268782,-0.535775,-0.292874,2.169558,0.478944,1.485337,2.325604,0.169153,...,0.605462,-0.201216,-2.461937,-5.197469,-11.409357,3.083988,-0.739473,-0.191106,1.048662,0
116,0.749202,-1.558879,0.310416,-0.288168,-0.461174,-1.093880,-0.252068,0.998455,-1.086828,-1.699237,...,-0.397384,-0.382962,1.873482,-1.091358,-19.551361,-3.260066,0.577704,1.202152,2.068529,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
457,-1.170605,-0.495832,0.142202,0.660402,-0.007976,1.208633,1.115681,-0.225352,-0.628384,-0.164183,...,0.691438,0.124177,0.575242,-0.841315,18.364583,2.058310,0.079025,-0.254831,-0.234857,1
158,-0.405478,0.213504,-1.474947,0.289924,0.527606,0.539427,2.415933,1.268000,2.027227,0.712843,...,0.828673,-2.025517,-1.286112,7.502770,7.662713,1.327710,-0.321164,-0.602094,-0.603647,0
366,0.219179,-1.079499,-0.851267,1.013682,3.597915,-4.673756,0.122112,1.124482,2.165549,-0.148559,...,0.153648,2.334710,-1.626425,0.567665,2.022773,6.187501,1.140586,0.960029,0.710593,1
298,-1.058108,-0.034290,0.265045,0.672128,1.586579,0.479597,0.648822,-0.186405,-1.559898,-0.650517,...,-1.185224,-0.692369,-1.095007,-3.738033,-11.477336,-0.748597,-0.960175,0.377919,-0.122229,0
118,-0.868739,-0.730965,2.296294,-0.152946,-6.155008,-0.779590,1.467751,0.602190,-0.819780,-0.090138,...,-1.391545,0.587823,-0.224474,3.953868,0.828049,0.418173,0.021831,-0.787920,0.315609,0

Haciendo cuentas tenemos que el porcentaje de positivos en el dataset original es 29,4. Por lo tanto si tenemos un test set de 100, necesitamos 29 positivos para que sea balanceado. Primero el shuffle igual, por loas dudas :).

In [8]:
def separar_desarrollo_evaluacion(datos, test_size=0.2):
    datos = datos.sample(frac=1)
    class_mask_1 = datos["target"]==1
    percentage_positive = len(datos[class_mask_1])/len(datos)
    test_positive_size = int(round(len(datos)*test_size*percentage_positive))

    df_test_pos = datos[class_mask_1][:test_positive_size]
    df_test_neg = datos[class_mask_0][:(int(len(datos)*test_size) - test_positive_size)]
    df_test = pd.concat((df_test_pos, df_test_neg))


    df_train_pos = datos[class_mask_1][test_positive_size:]
    df_train_neg = datos[class_mask_0][(int(len(datos)*test_size) - test_positive_size):]
    df_train = pd.concat((df_train_pos, df_train_neg))

    return df_test, df_train

test, train = separar_desarrollo_evaluacion(df)

C:\Users\magal\AppData\Local\Temp\ipykernel_41228\3246473514.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_test_neg = datos[class_mask_0][:(int(len(datos)*test_size) - test_positive_size)]
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\3246473514.py:13: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_train_neg = datos[class_mask_0][(int(len(datos)*test_size) - test_positive_size):]

## Ejercicio 2


### Construcción de modelos

Para este punto, la tarea consiste en construir y evaluar modelos de tipo **árbol de decisión**. Además, obtener una **estimación realista de la performance** de los mismos.

1. Entrenar un árbol de decisión con altura máxima 3 y el resto de los hiperparámetros en default.

1. Estimar la performance del modelo utilizando _K-fold cross validation_ con `K=5`, con las métricas _Accuracy_, _Area Under the Precision-Recall Curve (AUPRC)_, y _Area Under the Receiver Operating Characteristic Curve (AUCROC)_. 

   En esta oportunidad se va a pedir además de calcular las métricas para cada fold por separado y su promedio, que hagan el cálculo del score global (como vimos en clase), sólo para los folds de validación.
   
   Reportar el resultado en una tabla similar a:

      <table>
      <thead>
      <tr>
      <th align="center">Permutación</th>
      <th>Accuracy (training)</th>
      <th>Accuracy (validación)</th>
      <th>AUPRC (training)</th>
      <th>AUPRC (validación)</th>
      <th>AUC ROC (training)</th>
      <th>AUC ROC (validación)</th>
      </tr>
      </thead>
      <tbody>
      <tr>
      <td align="center">1</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      </tr>
      <tr>
      <td align="center">2</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      </tr>
      <tr>
      <td align="center">3</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      </tr>
      <tr>
      <td align="center">4</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      </tr>
      <tr>
      <td align="center">5</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      </tr>
      <tr>
      <td align="center">Promedios</td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      </tr>
      <td align="center">Global</td>
      <td>(NO) </td>
      <td></td>
      <td>(NO) </td>
      <td></td>
      <td>(NO) </td>
      <td></td>
      </tr>
      </tbody>
      </table>    
  
   **Importante**: de acá en más sólamente utilizaremos el score promedio cuando hagamos _K-fold cross-validation_.
 
1. Explorar las siguientes combinaciones de parámetros para  árboles de decisión (siguiendo con $k-fold$ con $k=5$) utilizando [ParameterGrid](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.ParameterGrid.html) de _scikit learn_. No está permitido utilizar `GridSearchCV` en este ejercicio.

   <table>
   <thead>
   <tr>
   <th align="center">Altura máxima</th>
   <th align="center">Criterio de corte</th>
   <th>Accuracy (training)</th>
   <th>Accuracy (validación)</th>
   </tr>
   </thead>
   <tbody><tr>
   <td align="center">3</td>
   <td align="center">Gini</td>
   <td></td>
   <td></td>
   </tr>
   <tr>
   <td align="center">5</td>
   <td align="center">Gini</td>
   <td></td>
   <td></td>
   </tr>
   <tr>
   <td align="center">Infinito</td>
   <td align="center">Gini</td>
   <td></td>
   <td></td>
   </tr>
   <tr>
   <td align="center">3</td>
   <td align="center">Entropía</td>
   <td></td>
   <td></td>
   </tr>
   <tr>
   <td align="center">5</td>
   <td align="center">Entropía</td>
   <td></td>
   <td></td>
   </tr>
   <tr>
   <td align="center">Infinito</td>
   <td align="center">Entropía</td>
   <td></td>
   <td></td>
   </tr>
   </tbody></table>

1. ¿Qué conclusiones se pueden sacar de estas tablas?

In [21]:
y_train = train.target
X_train = train.drop("target", axis=1)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
arbol = DecisionTreeClassifier()

In [ ]:
#from sklearn.model_selection import cross_val_score
#cross_val_score(arbol, X_train, y_train, cv=5)

In [105]:
X_train[X_train.index == 78]

,uAro,vIlg,VtZP,qTUs,bgVs,PdRG,CqGH,bfBD,ZtLG,SNCN,...,fufA,hnYp,cWwQ,GkqC,VHPu,KKxk,TNkz,GkcC,KSYM,YpTu
78,-0.71371,1.280427,-1.573188,-0.605755,2.320409,-3.477101,-1.163951,0.313675,-1.478643,2.403069,...,-1.004544,-0.144364,2.079022,0.166029,-6.613203,0.445157,4.29666,0.415249,-0.1205,-0.701048

In [116]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_validate
kfold = KFold(n_splits=5, shuffle=True, random_state=0)
results = cross_validate(arbol, X_train, y_train, cv=kfold, scoring=['accuracy', 'roc_auc', 'average_precision'],return_train_score=True, return_estimator=True, return_indices=True)
y_pred = np.zeros(400)
indexes = results['indices']['test'][0]
for i in range(5):
    estimator = results['estimator'][0]
    fold_predict = results['indices']['test'][0]
    for element in fold_predict:  
       y_pred[element] = estimator.predict(X_train[element:element+1])

np.sum(y_train == y_pred)/400

C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])
C:\Users\magal\AppData\Local\Temp\ipykernel_41228\2740230771.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  y_pred[element] = estimator.predict(X_train[element:element+1])

0.705

In [120]:
results['test_accuracy'].mean()

0.6699999999999999

In [136]:
from sklearn.model_selection import ParameterGrid
grid = ParameterGrid({"max_depth":[3, 5, None] , "criterion":["gini", "entropy"]})
for pair in grid:
    arbol = DecisionTreeClassifier(**pair)
    results = cross_validate(arbol, X_train, y_train, cv=kfold, scoring=['accuracy'],return_train_score=True)
    print(pair)
    print(results["test_accuracy"].mean())

{'criterion': 'gini', 'max_depth': 3}
0.6775
{'criterion': 'gini', 'max_depth': 5}
0.6875
{'criterion': 'gini', 'max_depth': None}
0.6625000000000001
{'criterion': 'entropy', 'max_depth': 3}
0.6799999999999999
{'criterion': 'entropy', 'max_depth': 5}
0.6824999999999999
{'criterion': 'entropy', 'max_depth': None}
0.675

## Ejercicio 3

### Comparación de algoritmos 

Se pide explorar distintas combinaciones de algoritmos de aprendizaje con diferentes configuraciones con el objetivo de **encontrar el mejor modelo** de cada familia de buscar la performance óptima. Para este ejercicio realizar una experimentación utilizando [`RandomizedSearchCV`](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.RandomizedSearchCV.html). Como métrica de performance usar AUCROC resultante de 5-fold cross-validation. 

Hiperparámetros_: Revisar la documentación de cada uno de los hiperparámetros para entender qué posibles hiperparámetros impacten de manera positiva en la construcción del algoritmo.

Documentación extra sobre [`Tuning hyper-parameters`](https://scikit-learn.org/stable/modules/grid_search.html), leer hasta 3.2.2.

1. Algoritmos a probar: 
  - Árboles de decisión. Mínimo 4 hiperparámetros.
  - KNN (k-vecinos más cercanos). Mínimo 3 hiperparámetros.
  - SVM (Support vector machine). Mínimo 2 hiperparámetros.

Detallar los hiperparámetros elegidos para cada algoritmo y explicar la razón del espacio de búsqueda considerado para cada uno de estos, ¿cuántas iteraciones usaron?. A su vez, reportar la performance asociada de aquellos que consideren relevantes (al menos la mejor combinación para cada algoritmo). 

2. Compare los resultados obtenidos en el ejercicio anterior con los siguientes modelos con sus hiperparámetros default. 

  - LDA (Linear discriminant analysis)
  - Naïve Bayes

¿Qué resultados obtuvo? ¿Qué hiperparámetros podrían ser relevantes explorar en estos modelos? ¿Por qué?

3. ¿Cuál fue el mejor modelo y con qué configuración? Explicar por qué creería que dio mejor (recordando qué hace cada algoritmo y con qué tipo de datos están trabajando).

In [138]:
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.model_selection import RandomizedSearchCV

In [195]:
arbol = DecisionTreeClassifier()
distribution = {'max_depth':range(1,6), 'criterion':['gini', 'entropy'], 'min_samples_split':range(2,3), 'max_features':[ 'sqrt', 'log2', None] }
rep = RandomizedSearchCV(arbol, distribution, cv = kfold, scoring='roc_auc',n_iter=30)
search = rep.fit(X_train, y_train)
search.best_params_

{'min_samples_split': 2,
 'max_features': None,
 'max_depth': 2,
 'criterion': 'entropy'}

In [204]:
nbg = GaussianNB()
cross_validate(nbg, X_train, y_train, cv=kfold)

{'fit_time': array([0.00715804, 0.00553203, 0.00392556, 0.0040369 , 0.0047822 ]),
 'score_time': array([0.00383663, 0.00302219, 0.00316954, 0.00401306, 0.00268912]),
 'test_score': array([0.775 , 0.75  , 0.7875, 0.75  , 0.7875])}

## Ejercicio 4: 
### Evaluación de performance

- La entrega del trabajo estará acompañada de una evaluación en la cual deberán poner a prueba su mejor modelo y sobre todo, su capacidad para estimar sus resultados. 

- Su tarea será estimar la performance (AUCROC) que tendrá su mejor modelo en datos de evaluación (X_held_out). 

- Para ello, deberán predecir las **probabilidades** (probabilidad de la clase positiva) de las distintas instancias con su modelo, enviarnos dichas probabilidades junto a una estimación con 4 decimales de cuál será el AUCROC resultante y calcularemos el resultado real. Consideraremos que el **mejor modelo será el que se encuentre más cerca del valor real que calcularemos luego de la entrega**.

- Recomendamos no perder de vista esta evaluación/competencia durante el desarrollo del TP, sobretodo en el momento de separar los datos en los primeros puntos. 

- Para que podamos evaluar la performance, junto con la entrega del informe, deberán enviar un archivo con el numero de grupo con dos digitos en formato csv con la columna `output` y el valor obtenido con 4 decimales (se subirá un ejemplo cuando se publiquen los datos de la competencia) y un valor esperado de AUCROC: `GG_y_pred_held_out_AUCROC`. 

    - Ej.: el grupo tres cree que obtuvo un valor de 0.7321 de AUCROC deberá submitear un archivo llamado: `03_y_pred_held_out_7321.csv`.

- Los datos podrán encontrarlos en este [link](https://github.com/aprendizaje-automatico-dc-uba-ar/material/tree/main/tp/01_aprendizaje_supervisado/datos).

- Las decisiones de este punto pueden desarrollarse hasta en una carilla, aunque con media debería alcanzar.

## Ejercicio 5: 
### Conclusiones

Escribir como mínimo en un párrafo, una conclusión del trabajo realizado, incluyendo problemas encontrados y 
aspectos no incluidos en el enunciado que hayan sido abordadas durante el desarrollo.

---
## Entregables
- Contarán con un esqueleto en formato Jupyter Notebook en donde podrán intercalar celdas para reportar y responder a los ítems de cada ejercicio. 
- Los entregrables serán
    - Un informe en formato .pdf (**digital**) que responda a los ítems de este enunciado respetando la cantidad de espacio máximo por cada ítem. Nombrarlo siguiendo el formato `GG_Nombre_de_grupo`
    - Adjuntar el notebook final en formatos .pdf e .ipynb. Es necesario que los resultados puedan reproducirse al ejecutar todas las celdas en orden (verificarlo haceindo: Kernel -> Restart and Run All). 
    - Las predicciones del *held out* del punto 4 en formato csv.
- Habrá una entrega intermedia obligatoria que deberán hacer antes de la fecha indicada en el campus. Para esta entrega deberán enviar el código que resuelve los primeros 3 ejercicios. 
- La **fecha** y **hora límite** de entrega está determinada en el campus de la materia.
- El trabajo deberá elaborarse en grupos de 4 personas.
- Se podrán pedir pruebas de integridad y autoría; es decir, verificar que la salida solicitada es fruto del modelo presentado y que el modelo fue construido según lo requerido en este enunciado.
- La evaluación será grupal y se basará en la calidad del informe (presentación, claridad, prolijidad); la originalidad, practicidad y coherencia técnica de la solución; la corrección y solidez de las pruebas realizadas.

### Importante: sobre el uso de ChatGPT y grandes modelos de lenguaje

En este trabajo no estará explícitamente prohibido pero si fuertemente desaconsejado, consideramos a este trabajo práctico una importante herramienta de aprendizaje donde el uso de GPT puede ser perjudicial. En caso de usarlo se pide aclararlo en el informe y especificar cómo y en donde se utilizó. Así como expresar su opinión sobre la respuesta generada por el modelo pudiendo estar a favor o en contra de lo propuesto por este. Pueden adjuntar el link a la conversación con el modelo.

**Nota**: Agradecemos a [Martín García Sola](https://ar.linkedin.com/in/martin-e-garcia-sola) por la asistencia biológica en la confección de este Trabajo Práctico.